### ISSUE TITLE
Import/Export error

### ISSUE THREAD

**Issue by Communard1871** [ALIENQuake/ProjectInfinity#23] opened 2021-06-24 20:51 UTC
**Upload logs from Logs folder**
[Logs.zip](https://github.com/ALIENQuake/ProjectInfinity/files/6712021/Logs.zip)

**Describe the bug**
When importing/exporting install order, some entries in the install entry are malformed, please see the entry for Sirine's Call (among others) in the below.
[ProjectInfinity-InstallSequence-2021.06.24-21꞉06.log](https://github.com/ALIENQuake/ProjectInfinity/files/6712023/ProjectInfinity-InstallSequence-2021.06.24-21.06.log)
Line reads:
SirinesCall-Main;The Lure of the Sirine's Call - The Lure of the Sirine's Call
Should read:
SirinesCall:0;The Lure of the Sirine's Call - The Lure of the Sirine's Call

**To Reproduce**
1. Set up an install sequence containing Lure of the Sirine's Call mod
2. Click E
3. Save "SortingOrder.csv"
4. Click I, import "SortingOrder.csv"
5. Observe incorrect line in install sequence, attempt to install to observe "Unknown Argument" error caused and install failure.

**Expected behavior**
SortingOrder.csv export should create a list with correct entries.
**Screenshots**
N/A

**Comment by ALIENQuake** [comment] 2021-06-24 22:02
@Communard1871 It's not an error. It's actually a new feature.

**Comment by Communard1871** [comment] 2021-06-24 22:03
Can you explain? When it imports it creates an installation error when attempting to install, how can this be intended?

**Comment by ALIENQuake** [comment] 2021-06-24 22:15
@Communard1871 I cannot reproduce this error. Having this single mod inside install sequence prodce no error on my side. I can import/exprot it without problem. I will investigate and get back to you.

**Comment by ALIENQuake** [comment] 2021-06-24 23:13
@Communard1871 Ok, I can reproduce. It's the whitespace characters inside the install sequence. It will be fixed, thanks for reporting. 😃

**Comment by Communard1871** [comment] 2021-06-24 23:18
No worries! thank you for solving so quickly!

**Comment by ALIENQuake** [comment] 2021-06-25 14:12
@Communard1871 Can you update to 0.9.3 and create a new install sequence with Lure of the Sirine's Call mod, export it to a new file, import it, and then install? Remember to use a separate game copy for testing.

**Closed** 2021-06-25 17:04 UTC
Labels: bug
