### ISSUE TITLE
A seemingly correctly defined dynamic install order gives a false positive

### ISSUE THREAD

**Issue by RobertPeetsalu** [ALIENQuake/ProjectInfinity#21] opened 2021-01-30 10:33 UTC
**Check requirements:**
 - OS: 64-bit, fully updated Windows 10
 - .NET framework 4.0.30319

**Upload logs from Logs folder**
[Logs.zip](https://github.com/ALIENQuake/ProjectInfinity/files/5897765/Logs.zip)

**Describe the bug**
A seemingly correctly defined dynamic install order gives a false positive

**To Reproduce**
1. Open Project Infinity 0.8.12
2. Download and extract HiddenGameplayOptions v2.6 and cdtweaks v9 mods
3. Load them to Project Infinity
4. Move cdtweaks from Default/Unassigned to After A.I.
5. Move HiddenGameplayOptions from Default/Unassigned to Late (strange that it starts in Default/Unassigned although it's HiddenGameplayOptions.ini file says "# Dynamic Install Order Category Type = Late")
4. Select some components from both mods
5. A rule displays HiddenGameplayOptions AFTER cdtweaks as FALSE

**Expected behavior**
The rule should return TRUE, because HiddenGameplayOptions.ini says "After = cdtweaks" and "cdtweaks" is the correct name to use - same as in the .tp2 file name after "setup-":
![2021-01-30 12_03_34-C__Users_rober_Documents_Baldur's Gate mods_Tweaks-Anthology_cdtweaks](https://user-images.githubusercontent.com/892058/106353845-33795a80-62f6-11eb-90a5-0b9b7ce70cc8.png)

**Screenshots**
![2021-01-30 11_45_17-Project Infinity 0 8 12](https://user-images.githubusercontent.com/892058/106353868-4d1aa200-62f6-11eb-9bfb-1443301df036.png)

I assume that selected components and other selected mods are not important for this bug report, but if the bug doesn't reproduce and you need more details, please let me know.

**Comment by ALIENQuake** [comment] 2021-01-30 11:31
@RobertPeetsalu I'm not able to reproduce this. But I found one issue with Up/Down/Top/Bottom buttons and fixed it. Can you try to reproduce it by using 0.8.14?

BTW: The "# Dynamic Install Order Category Type = Late" is not implemented yet as the main functionality of the feature have yet to be decided.

**Comment by RobertPeetsalu** [comment] 2021-01-30 16:57
I managed to reproduce it with 
- PI 0.8.14, 
- while only selecting the first component of both mods,
- without using the up/down/top/bottom arrows, using drag and drop instead. 

More precise steps to reproduce:
1. Download and extract into the mods folder HiddenGameplayOptions v2.6 and cdtweaks v9 mods (or probably any other 2 mods, one of which has a dynamic install order rule defined about the other) in some way **that will make them both appear in the Default/Unassigned category upon their first scanning into PI**. For example download .zip files from GitHub and extract in the mods folder before launching PI.
2. Open Project Infinity 0.8.14 and scan the 2 mods in. They now reside in the Default/Unassigned category.
3. Drag and drop cdtweaks to After A.I. and HiddenGameplayOptions to Late category (doesn't matter which you drag first)
4. Select any component from both mods.
5. A rule displays HiddenGameplayOptions AFTER cdtweaks as FALSE

This bug doesn't occur if on first scan the mod is set in a category, in which it would end up fulfilling the install order rule (e.g. when installing Tweaks-Anthology from the PI-s green button) although even then the bug can be reproduced if install order file (ProjectInfinity-Mods-Assignment.txt) is deleted and mods are rescanned, so the versions and contents of mods shouldn't matter.

**Comment by ALIENQuake** [comment] 2021-01-30 17:31
@RobertPeetsalu I was able to reproduce this, thanks for the detailed steps, I will fix this.

**Comment by ALIENQuake** [comment] 2021-04-22 08:03
@RobertPeetsalu Fixed via 0.8.15

**Closed by ALIENQuake** 2021-04-22 08:03 UTC
Labels: bug
